name: Publish DeepStack Documentation to Docker
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Docker Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: deepquestai/deepstack-docs
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_ACCESS }}
        tags: "latest, 2022.04.1"
        default_branch: main
        dockerfile: Dockerfile